### ISSUE TITLE
Use of an iteratee's

### ISSUE THREAD

**Issue by urv** [urv/fixhs#8]
Use of an iteratee for reading from the socket, or maybe make use as well of attoparsec-iteratee (See monad reader issue 16 about iteratees)

**Comment by yveshauser** [comment]
Probably we could get rid of the socket connection entirely and only provide the fix parser in order for people to be free to use their favorite stream processor library. What do you think?

**Comment by urv** [comment]
Yes I completely agree with you on this.

**Comment by yveshauser** [comment]
Removed the socket connection code (seemed to be dead anyway) in order to have a pure parser library.
